---
###
#
#   This runs on localhost to create the ispconfig instance on linode
#

- name: Create Linode and run initial setup
  hosts: localhost
  gather_facts: false
  vars:
    linode_token: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      33383163353965616566616230303233636265386130653936353330653332383633653839366130
      3262623330623662373764353738336231643761666162620a376464383766656262353165356565
      30666636653664316165633137386463356339303838313061323438333563326638633131333965
      3939353837663533340a313331303465653135616563646262373232626433366439366331326130
      32376264383335393061336561643563393938663139363635636538396565616566393239623931
      33373266333130376532336633363931663237353438323961623232343831306432363131663165
      63316332316636393434356136396437366539636466306439316530366539623231306136326135
      30333161653566376565
    linode_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      36633034373034356664306136633738393834326134383830366331353664343133306439373133
      6637396361353466653536393333373037303562633865390a636663666335646264626532643439
      65383564316230323961653463323762663138333163633066333236393862653833333764343734
      3033666138303630630a653461626632646331643739646432323962653361356564326464616565
      65303435616165303335303330363536343664653233396434323534643937363162
    instance_label: fleur

  tasks:
    - name: Create Linode instance
      linode.cloud.instance:
        api_token: "{{ linode_token }}"
        label: "{{ instance_label }}"
        type: g6-standard-2
        region: us-central
        image: linode/debian12
        root_pass: "{{ linode_password }}"
        state: present
      register: linode_instance

    - name: Display IP address
      debug:
        msg: "Linode IP: {{ linode_instance.instance.ipv4[0] }}"

    # Pepare the new linode so we can run a configure script
    # Note: this usses the ipv4 address as the name.
    - name: Add new instance to inventory
      add_host:
        name: "{{ linode_instance.instance.ipv4[0] }}"
        groups: new_linode
        ansible_user: root
        ansible_ssh_pass: "{{ linode_password }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

    - name: Wait for SSH to be available
      wait_for:
        host: "{{ linode_instance.instance.ipv4[0] }}"
        port: 22
        delay: 30
        timeout: 300
        state: started

    # Somtimes addresses are reused
    - name: Add new instance to inventory
      add_host:
        name: "{{ linode_instance.instance.ipv4[0] }}"
        groups: new_linode
        ansible_user: root
        ansible_ssh_pass: "{{ linode_password }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

#################################################
#
# This runs on the new ispconfig instance created as root
#
- name: Run initial configuration on new Linode
  hosts: new_linode
  gather_facts: true

  vars:
    ansible_user: root
    username: lavender
    new_hostname: fleur
    fqdn: fleur.lavnet.net

  tasks:
    # TODO might need to upgrade for ispconfig...not doing now.
    - name: Update apt cache
      apt:
        update_cache: yes

    # TODO Review this list, I do need these for a persent image.
    - name: Install basic packages
      apt:
        name:
          - vim
          - htop
          - curl
          - git
        state: present

    # This is the provisioning user
    # TODO SMELL   break from using standard user space!!!!!
    - name: Create user lavender
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
        home: "/home/{{ username }}"
        createhome: yes
        state: present

    - name: Add user to sudo
      ansible.builtin.user:
        name: "{{ username }}"
        groups: sudo
        append: yes

    - name: Create .ssh directory
      ansible.builtin.file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0700"

    - name: Copy SSH public key to authorized_keys
      ansible.builtin.copy:
        src: "~/.ssh/id_ed25519.pub"
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0600"

    # TODO: make this inner playbook not idempotent
    - name: set hostname to match inventory
      ansible.builtin.command: "/usr/bin/hostnamectl --static set-hostname {{ fqdn | lower }}"
      changed_when: false

    #  TODO SMELL:  this feels legacy, needs to be tested
    - name: Ensure localhost entry exists in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1 {{ fqdn }} {{ new_hostname}}"
        state: present

    - name: Add server IP to /etc/hosts with hostname and FQDN
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "^{{ inventory_hostname }}"
        line: "{{ inventory_hostname }} {{ fqdn }} {{ new_hostname }}"
        state: present

    # ..................................................................
    # wget -O - https://get.ispconfig.org | bash -s -- --channel=stable --use-php=8.2,8.3 --no-quota --no-ftp --ssh-harden --unattended-upgrades=autoclean,reboot --ssh-permit-root=without-password --ssh-password-authentication=no --i-know-what-i-am-doing

    # - name: Run ISPConfig installer script
    #   shell: |
    #     wget -O ispconfig_installer.sh https://get.ispconfig.org
    #     bash ispconfig_installer.sh --channel=stable --use-php=8.2,8.3 --no-quota --no-ftp --ssh-harden --unattended-upgrades=autoclean,reboot --ssh-permit-root=without-password --ssh-password-authentication=no --i-know-what-i-am-doing
    #   args:
    #     executable: /bin/bash
    #     # Prevent the task from reporting changed every time
    #     creates: /usr/local/ispconfig # Won't run if this path exists
    #   register: ispconfig_install
    #   # This can take a while, setting a longer timeout
    #   async: 7200
    #   poll: 30

    # - name: Download ISPConfig installer
    #   get_url:
    #     url: https://get.ispconfig.org
    #     dest: /root/ispconfig_installer.sh
    #     mode: "0755"

    # - name: Run ISPConfig installer with yes
    #   shell: bash /root/ispconfig_installer.sh --channel=stable --use-php=8.2,8.3 --no-quota --no-ftp --ssh-harden --unattended-upgrades=autoclean,reboot --ssh-permit-root=without-password --ssh-password-authentication=no --i-know-what-i-am-doing
    #   args:
    #     creates: /usr/local/ispconfig
    #   register: ispconfig_install
    #   async: 3600
    #   poll: 30

    # - name: Display ISPConfig installation output
    #   debug:
    #     var: ispconfig_install
    #   when: ispconfig_install is defined

    # - name: Display ISPConfig installation output
    #   debug:
    #     var: ispconfig_install.stdout_lines
    #   when: ispconfig_install.stdout is defined

    # # ..................................................................

    # - name: Extract ISPConfig admin password from log
    #   shell: grep -i "password" /tmp/ispconfig_setup.log | grep -i "admin" || echo "Password not found in log"
    #   register: admin_password
    #   changed_when: false
    #   ignore_errors: true

    # - name: Display ISPConfig admin password
    #   debug:
    #     msg: "ISPConfig admin password: {{ admin_password.stdout }}"
    #   when: admin_password.stdout is defined

    # # ..................................................................

    # - name: Capture ISPConfig installation log with passwords
    #   fetch:
    #     src: /tmp/ispconfig_setup.log
    #     dest: ./ispconfig_logs/{{ inventory_hostname }}-setup.log
    #     flat: yes
    #   ignore_errors: true # In case the file location is different

    # - name: Look for other potential ISPConfig log files
    #   find:
    #     paths: /tmp
    #     patterns: "*ispconfig*.log"
    #   register: ispconfig_logs
    #   when: ispconfig_install.changed | default(false)

    # - name: Ensure ispconfig_logs directory exists locally
    #   file:
    #     path: "./ispconfig_logs"
    #     state: directory
    #     mode: "0755"
    #   delegate_to: localhost

    # - name: Fetch any found ISPConfig log files
    #   fetch:
    #     src: "{{ item.path }}"
    #     dest: ./ispconfig_logs/{{ inventory_hostname }}-{{ item.path | basename }}
    #     flat: yes
    #   with_items: "{{ ispconfig_logs.files | default([]) }}"
    #   when: ispconfig_logs.files is defined and ispconfig_logs.files | length > 0
